name: DVC CI
on:
  push:
    branches:
      - main  # Или ваша ветка продакшена
jobs:
  dvc-setup-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install DVC
        run: pip install dvc
        
      - name: Install DVC Yandex Disk
        run: pip install dvc[yandex]

      - name: Configure DVC Remote
        run: |
           dvc remote add -d yandex-remote rclone:yandex:/MLOps_dvc
           
      - name: Configure DVC Remote Credentials
        run: |
           dvc remote modify yandex-remote access_key_id ${{ secrets.YANDEX_ACCESS_KEY_ID }}
           dvc remote modify yandex-remote secret_access_key ${{ secrets.YANDEX_SECRET_ACCESS_KEY }}
           dvc remote modify yandex-remote endpointurl https://storage.yandexcloud.net
           
      - name: DVC Pull Data
        run: dvc pull  # Скачиваем все зависимости

      - name: Run DVC Pipeline
        run: dvc repro  # Запускаем пайплайн

      - name: DVC Push Data
        run: dvc push  # Отправляем результаты

      - name: Git add and commit DVC files
        run: |
          git config user.email "github-actions@example.com"
          git config user.name "GitHub Actions"
          git add .dvc dvc.lock
    
          if [[ $(git status --porcelain | grep -c "dvc.lock\|.dvc") -ne 0 ]]; then
            git commit -m "Update DVC data"
          else
            echo "No changes to commit"
          fi

      - name: Git push DVC Config
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          branch: ${{ github.ref }}
